import StyledComponentsRegistry from '@/lib/registry/styled-components';

import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
    </html>
  );
}
